### ISSUE TITLE
训练中 第一个循环后报错 RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ck6698000** [yuantn/MI-AOD#36]
google了相应的问题，发现mmdet中如果CUDA runtime version和 compiler version不匹配就会有这种报错。

然而问题是模型已经正常训练了一个循环，也生成了.npy的权重文件，但在进入下一个循环时突然报错。按理说不是会在正常训练前就报错吗？会不会是有什么其他的原因导致错误呢？

系统环境：
CentOS 6.3 
CUDA9.0         Conda中安装了9.2的toolkit
其余按照安装说明操作。

log日志如下：
99.9%
99.9%
99.9%
100.0%
100.0%
100.0%
100.0%
100.0%
100.0%
100.0%
2021-08-21 21:24:18,266 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "./tools/train.py", line 257, in <module>
    main()
  File "./tools/train.py", line 170, in main
    distributed=distributed, validate=(not args.no_validate), timestamp=timestamp, meta=meta)
  File "/home/disk2/vis/wrs/proj/MI-AOD/mmdet/apis/train.py", line 75, in train_detector
    broadcast_buffers=False, find_unused_parameters=True)
  File "/home/disk2/vis/wrs/envs/miaod/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 333, in __init__
    self.broadcast_bucket_size)
  File "/home/disk2/vis/wrs/envs/miaod/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 549, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: CUDA error: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "/home/disk2/vis/wrs/envs/miaod/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/disk2/vis/wrs/envs/miaod/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/disk2/vis/wrs/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/disk2/vis/wrs/envs/miaod/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/disk2/vis/wrs/envs/miaod/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/MIAOD.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by ck6698000** [comment]
理解错了 训练根本没有开始 然后直接报错

**Comment by andrew-begain** [comment]
@ck6698000 我也遇到了同样的问题，麻烦问下你是怎么解决的呢？谢谢

**Comment by ck6698000** [comment]
> @ck6698000 我也遇到了同样的问题，麻烦问下你是怎么解决的呢？谢谢

还是不匹配

**Comment by andrew-begain** [comment]
> 



> > @ck6698000 我也遇到了同样的问题，麻烦问下你是怎么解决的呢？谢谢
> 
> 还是不匹配

那你也是比较新的显卡是吧？虚拟环境下cuda为10.2就会有问题

**Comment by ck6698000** [comment]
> > 
> 
> > > @ck6698000 我也遇到了同样的问题，麻烦问下你是怎么解决的呢？谢谢
> > 
> > 
> > 还是不匹配
> 
> 那你也是比较新的显卡是吧？虚拟环境下cuda为10.2就会有问题

不 应该是本机CUDA和环境下cuda不匹配

**Comment by andrew-begain** [comment]
> > > 
> > 
> > 
> > > > @ck6698000 我也遇到了同样的问题，麻烦问下你是怎么解决的呢？谢谢
> > > 
> > > 
> > > 还是不匹配
> > 
> > 
> > 那你也是比较新的显卡是吧？虚拟环境下cuda为10.2就会有问题
> 
> 不 应该是本机CUDA和环境下cuda不匹配

那要是这样的话把本机的cuda设置一个软连接，链接到你的虚拟环境是不是就可以解决了呢？

**Comment by ck6698000** [comment]
> > > > 
> > > 
> > > 
> > > > > @ck6698000 我也遇到了同样的问题，麻烦问下你是怎么解决的呢？谢谢
> > > > 
> > > > 
> > > > 还是不匹配
> > > 
> > > 
> > > 那你也是比较新的显卡是吧？虚拟环境下cuda为10.2就会有问题
> > 
> > 
> > 不 应该是本机CUDA和环境下cuda不匹配
> 
> 那要是这样的话把本机的cuda设置一个软连接，链接到你的虚拟环境是不是就可以解决了呢？

pytorch等包会依赖cuda版本的啊 所以还是一致比较好吧
